### ISSUE TITLE
[PHP 7] PHP Fatal error: Redefinition of parameter $_

### ISSUE THREAD

**Issue by rfc2822** [wirecard/prestashop-wcs#4]
The plugin seems to be broken with PHP 7:

```
Oct 23 13:53:12 tyr php-fpm: PHP Fatal error:  Redefinition of parameter $_ in /srv/www/dev001.net/prestashop/modules/wirecardceecheckoutseamless/vendor/GuzzleHttp/Ring/Client/StreamHandler.php on line 313
```

Is it possible to get the plugin working with PHP 7?

**Comment by jakubpolomsky** [comment]
Hi! Thank you for your input. The guzzle library will be updated soon (https://github.com/guzzle/guzzle/issues/1015). In the meantime you can replace the guzzle library with a newer one.

**Comment by rfc2822** [comment]
Thanks, I will try that.

**Comment by rfc2822** [comment]
I have now replaced the Guzzle library, but the payment solution "is not available" in PrestaShop, although it appears as a module and I can do settings etc.

Will PHP7 be officially supported soon?

**Comment by devvv4ever** [comment]
Hi Jakub,
any ETA on the guzzle lib update? Thank you for your work!

**Comment by jakubpolomsky** [comment]
Hi!

Currently working on the update for Prestashop 1.7 where the php7 compatibility will be implemented. If everything goes ok, it will be released this week and the tweak applied for the 1.6 as well. So to answer your question: ETA possibly friday this week.

Regards!

**Comment by rfc2822** [comment]
Thanks!

At the moment, I have installed `guzzlehttp/guzzle=5.3.1` + dependencies with composer and then inserted `require("vendor/autoload.php");` into `wirecardcee_autoload.php`, which seems to work.

However, I now have the problem that every payment method seems to require the customer's birthday, although the guest checkout doesn't even ask for a birthday (and I think it should not be required). I'll open another issue for that.

**Comment by jakubpolomsky** [comment]
Thank you, open it and I'll have a look into it with the next release too.
